name: CI

on: push

jobs:
  commit-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout latest commit

    - name: Start embed API
      run: docker compose up -d --build --wait

    - name: Build PHP metadata extractor
      run: docker compose build php-metadata

    - name: Run tests
      run: bash run_tests.sh

    - name: Stop embed API
      if: always()
      run: docker compose down
